### ISSUE TITLE
Possible issue with version of Preferences in dependencies

### ISSUE THREAD

**Issue by MattB242** [Red-Portal/WidebandDoA.jl#1]
Hi - just downloaded your code for a project. 

When running the test suite as suggested in the README, I get the following error

`LoadError:MethodError:no method matching set_preferences!(::String, ::Pair{::String, ::String}) `

This appears to be because that specific method is not implemented in the version of Preferences (1.4.1) which is installed when you develop the  package. It's easily solved by updating to the latest v1.4.3, where that method appears to exist, but I thought you might like to know.

**Comment by Red-Portal** [comment]
Hi @MattB242 ! Thanks for the heads up! That's a bit weird given the CI never failed :thinking: But I tightened the version constraint for `Preferences`, so it shouldn't happen again.
